modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/astryxion/Alexs-Mobs-NeoForge/issues"

[[mods]]
modId="alexsmobs"
version="26.2-1.2.0"
displayName="Alex's Mobs (NeoForge)"
displayURL="https://github.com/astryxion/Alexs-Mobs-NeoForge"
bannerFile="alexs_mobs.png"
iconFile="alexs_mobs.png"
authors="Astryxion"
credits="Alexthe666, Carro1001, Paint_Ninja, Raguto"
description='''New, original, engaging, and aesthetic mobs for Minecraft.'''

[[mixins]]
config = "mixins.alexsmobs.json"

[[dependencies.alexsmobs]]
    modId="citadel"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alexsmobs]]
    modId="neoforge"
    mandatory=true
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alexsmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"

[modproperties.alexsmobs]
    catalogueItemIcon="alexsmobs:bear_dust"
